name: Conditionals

on:
  push:
  pull_request:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Only on main
        if: github.ref == 'refs/heads/main'
        run: echo "Main branch"

      - name: Fail step
        run: exit 1

      - name: Run after failure
        if: failure()
        run: echo "Previous step failed"

      - name: Continue even if error
        continue-on-error: true
        run: exit 1

  push-only:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Only runs on push"
