name: Secret Demo

on:
  push:

jobs:
  secret-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secret Exists
        run: |
          if [ -z "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The secret is set: false"
          else
            echo "The secret is set: true"
          fi

      - name: Try Printing Secret
        run: echo "Secret value is: ${{ secrets.MY_SECRET_MESSAGE }}"
